# -*- coding: utf-8 -*-
"""Keras_image_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12r7W-Qd7MBmUDl6l25Zq3zu-t3tK7BmW
"""

import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

def plot_image(index):
  plt.figure(figsize=(10,1))
  plt.imshow(x_train[index])

plot_image(0)

tf.config.experimental.list_physical_devices()



classes = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

x_train_scaled = x_train/255
x_test_scaled = x_test/255

"""HOT_CODING_y"""

categorical_y_train = keras.utils.to_categorical(y_train, 10)
categorical_y_train.shape

categorical_y_test = keras.utils.to_categorical(y_test, 10)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000, activation='relu'),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
]
)
model.compile(
    optimizer='SGD',
    loss= "categorical_crossentropy",
    metrics=['accuracy']
)
model.fit(x_train_scaled, categorical_y_train, epochs=50)

classes[np.argmax(model.predict(x_test_scaled)[0])]

classes[y_test[0][0]]

